# SPDX-License-Identifier: MIT
# KVM Network Role - handlers/main.yml

- name: restart libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted

- name: refresh network
  community.libvirt.virt_net:
    name: "{{ item.name }}"
    command: refresh
