# SPDX-License-Identifier: MIT
# Proxmox Firewall Role - handlers/main.yml

- name: reload pve-firewall
  ansible.builtin.systemd:
    name: pve-firewall
    state: reloaded

- name: restart pve-firewall
  ansible.builtin.systemd:
    name: pve-firewall
    state: restarted
