# SPDX-License-Identifier: MIT
# KVM Install Role - handlers/main.yml

- name: restart libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
    daemon_reload: true

- name: reload libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: reloaded

- name: restart default network
  community.libvirt.virt_net:
    name: default
    state: inactive

- name: restart default storage pool
  community.libvirt.virt_pool:
    name: default
    state: inactive
