# SPDX-License-Identifier: MIT
# Proxmox HA Role - meta/main.yml

galaxy_info:
  role_name: proxmox_ha
  description: Configure high availability groups and resources on Proxmox VE
  author: pulsar
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies:
  - role: proxmox_cluster
