# SPDX-License-Identifier: MIT
# KVM Storage Role - meta/main.yml

galaxy_info:
  role_name: kvm_storage
  description: Configure libvirt storage pools for KVM
  author: proxmox-kvm-swissknife
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies:
  - role: kvm_install
