# SPDX-License-Identifier: MIT
# Proxmox Install Role - meta/main.yml

galaxy_info:
  role_name: proxmox_install
  description: Install and configure Proxmox VE
  author: pulsar
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
