linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - prealloc
    - revive
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocyclo
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: false
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: github.com/pulsar

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
        - gosec
        - gocritic

run:
  timeout: 5m
  modules-download-mode: readonly
