# SPDX-License-Identifier: MIT
# Proxmox Storage Role - meta/main.yml

galaxy_info:
  role_name: proxmox_storage
  description: Configure Proxmox VE storage backends
  author: proxmox-kvm-swissknife
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
